### ISSUE TITLE
CUDA Setup failed despite GPU being available.

### ISSUE THREAD

**Issue by ZhenyaPav** [evshiron/rocm_lab#11]
I'm trying to get text-generation-webui to work on Arch. I've installed rocm5.6, and followed the installation steps to install text-gen-webui on RDNA3. But when launching, I get the following error:

```
CUDA SETUP: Loading binary /home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_hip_nohipblaslt.so...
libhipblas.so.0: cannot open shared object file: No such file or directory
CUDA SETUP: Loading binary /home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_hip_nohipblaslt.so...
libhipblas.so.0: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "/home/zhenyapav/Projects/text-generation-webui/server.py", line 28, in <module>
    from modules import (
  File "/home/zhenyapav/Projects/text-generation-webui/modules/chat.py", line 16, in <module>
    from modules.text_generation import (
  File "/home/zhenyapav/Projects/text-generation-webui/modules/text_generation.py", line 22, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/zhenyapav/Projects/text-generation-webui/modules/models.py", line 10, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/accelerate/utils/bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/zhenyapav/Projects/text-generation-webui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 22, in <module>
```

I have looked at my rocm installation, there are libraries libhipblas.so, libhipblas.so.1, libhipblas.so.1.0, but no libhipblas.so.0. But it isn't present in the docker image I used before either, so that's probably not the cause of the issue.

**Comment by evshiron** [comment]
`pip3 uninstall bitsandbytes` should do the trick.

AutoGPTQ just adds support for ROCm days ago, you can do `ROCM_VERSION=5.6 pip3 install auto-gptq` and it should work (and quantization works too). I haven't used BitsAndBytes for a long time due to bad ROCm support and low performance.

If it doesn't compile, please report back, and try this:

Clone https://github.com/PanQiWei/AutoGPTQ, add these lines:

```cpp
__host__ __forceinline__ hipblasStatus_t hipblasHgemm(hipblasHandle_t    handle,
                                                               hipblasOperation_t transA,
                                                               hipblasOperation_t transB,
                                                               int                m,
                                                               int                n,
                                                               int                k,
                                                               const half*        alpha,
                                                               const half*        AP,
                                                               int                lda,
                                                               const half*        BP,
                                                               int                ldb,
                                                               const half*        beta,
                                                               half*              CP,
                                                               int                ldc) {
    return hipblasHgemm(handle, transA, transB, m, n, k,
                        reinterpret_cast<const hipblasHalf *>(alpha),
                        reinterpret_cast<const hipblasHalf *>(AP), lda,
                        reinterpret_cast<const hipblasHalf *>(BP), ldb,
                        reinterpret_cast<const hipblasHalf *>(beta),
                        reinterpret_cast<hipblasHalf *>(CP), ldc);
}
```

to `autogptq_cuda/exllama/hip_compat.cuh`, and then `cd AutoGPTQ && pip3 install -e .`.

If there is a need, I might check and update BitsAndBytes builds in this repo for ROCm 5.6 compatibility, but no new feature will be supported.

Btw, I have a plan to update the article about `text-generation-webui`, but haven't had time to do it.

**Comment by ZhenyaPav** [comment]
Removing bitsandbytes removes the issue. ExLlama works fine. Haven't tried auto-gptq yet.

**Comment by ZhenyaPav** [comment]
Running `pip3 install -e .` fails with this error:

```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/zhenyapav/Projects/text-generation-webui/repositories/AutoGPTQ/setup.py", line 52, in <module>
          CUDA_VERSION = "".join(os.environ.get("CUDA_VERSION", default_cuda_version).split("."))
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

It does work with `ROCM_VERSION=5.6 pip install .`

**Comment by evshiron** [comment]
@ZhenyaPav 

Yeah. You have to add that `ROCM_VERSION=5.6` to build it for ROCm, at least for now.
